export const elementDesignTypes = {
    action: 'Tasks',
    attachment:'Attachment',
    businessUnit: 'Business Unit',
    checkBox: 'Checkbox',
    currency: 'Currency',
    date: 'Date',
    dateTime: 'Date/Time',
    decimal: 'Decimal',
    divider: 'Divider',
    dropDown: 'Dropdown',
    formHeading: 'Form Heading',
    groupHeading: 'GroupHeading',
    html: 'HTML',
    image: 'Image',
    integer: 'Integer',
    label: 'Label',
    radioButton: 'Radio Buttons',
    sectionHeading: 'Title',
    signature: 'Signature',
    text: 'Text',
    textArea: 'Textarea',
    time: 'Time',
    url: 'URL'
};