export const elementDesign = {
    alternateText: 'alternateText',
    attachment: 'Attachment',
    attachmentBind: 'attachmentBind',
    bind: 'bind',
    col: 'col',
    defaultValue: 'defaultValue',
    description: 'description',
    html: 'html',
    image: 'src',
    isShow: 'isShow',
    label: 'label',
    mandatoryOperator: 'mandatoryOperator',
    maxLength: 'maxLength',
    maxValue: 'maxValue',
    minLength: 'minLength',
    minValue: 'minValue',
    noIcon:'noIcon',
    options: 'options',
    placeholder: 'placeholder',
    referenceIndex: 'referenceIndex',
    required: 'required',
    row: 'row',
    signatureType: 'signatureType',
    signatureUser: 'SignatureUser',
    title: 'title',
    type: 'type',
    url: 'url'
};